<?php

use Drupal\Core\Link;
use Drupal\Core\Render\Markup;
use Drupal\file\Element\ManagedFile;
use Drupal\file\Entity\File;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;
use Drupal\webform\Entity\WebformSubmission;

/**
 * @file
 * Primary module hooks for Virtus module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */



function virtus_theme_suggestions_alter(array &$suggestions, array $variables, $hook)
{
  if ($hook === 'node') {
    /**
     * @var Node
     */
    $node = $variables['elements']['#node'];
    if ($node->bundle() === 'recurso') {
      $category = Term::load($node->get('field_categoria')->getValue()[0]['target_id']);
      $suggestions[] = 'node__' . $node->bundle() . '__' . strtolower($category->getName()) . '__' . $variables['elements']['#view_mode'];
    }
  }
}


function virtus_webform_submission_insert(WebformSubmission $webform)
{

  if ($webform->getWebform()->id() === 'subir_documento') {

    $data = $webform->getData();


    $uploaded_file = $data['archivo'];
    $resource_url = $data['url_del_recurso'];
    $programming_level = $data['nivel_de_programacion'];
    $allow_download = $data['permitir_descarga'];
    $allow_comments = $data['permitir_aportes'];
    $categories = $data['categorias_asociadas'];


    $file = NULL;
    if ($uploaded_file) {
      $file = File::load($uploaded_file);
    }


    if (!empty($resource_url)) {
      $info = pathinfo($resource_url);
    } else {
      $info = pathinfo($file->getFileUri());
    }


    $node = Node::create([
      'type' => 'recurso',
      'title' => $info['filename'],
      'field_categoria' => $categories[0],
      'field_permitir_descarga' =>  $allow_download,
      'field_permitir_comentarios' => $allow_comments,
      'field_nivel' => $programming_level,
      'status' => 'published'
    ]);

    $category = Term::load($categories[0]);
    $categoryName = strtolower($category->getName());

    if ($categoryName === 'documental' || $categoryName === 'presentación') {
      $node->set('field_url', $resource_url);
      $node->set('field_archivo', $uploaded_file);
    }

    if ($categoryName === 'entrevista') {
      $node->set('field_url', $resource_url);
    }

    if ($categoryName === 'paper' || $categoryName === 'tutorial') {
      if ($file) {
        $node->set('field_archivo', $uploaded_file);
      } else {
        $node->set('field_url', $resource_url);
      }
    }

    $node->save();

    \Drupal::messenger()->addMessage('Se ha creado una nueva entrada de contenido: ' . Markup::create(
      Link::fromTextAndUrl(
        $node->getTitle(),
        $node->toUrl('canonical')
      )->toString()
    ));
  }
}
